# MTLTH Stellar Anchor <https://mtlth.montelibero.org>
# https://github.com/stellar/stellar-protocol/tree/master/ecosystem
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
VERSION="2.5.0"

ACCOUNTS=[
"GAEAAQ6GYMF6SSAWSW3MSLWB5LHYQIEGF3I3TUBJM6L3MSZYSPOMTLTH"
]

[DOCUMENTATION]
ORG_NAME="MTL Thailand Assets (MTLTH)"
ORG_DBA="MTL Thailand Assets (MTLTH)"
ORG_URL="https://mtlth.montelibero.org"
ORG_LOGO="https://mtlth.montelibero.org/stellar-images/mtlth-logo.png"
ORG_DESCRIPTION="MTLTH is a decentralized autonomous organization (DAO) for tokenized assets in Thailand, empowering financial freedom and investment opportunities, operating in accordance with the principles and values of a free society. The top 20 shareholders are members of the Fund's Board of Directors, participating in the formulation and adoption of all decisions. The Fund is a corporate member and verifier of MTLA and provides an identity verification process for MTLA members."
ORG_GITHUB="montelibero-org"
ORG_PHYSICAL_ADDRESS = "Thailand"
ORG_OFFICIAL_EMAIL="thailand@montelibero.org"
ORG_SUPPORT_EMAIL="thailand@montelibero.org"

[[CURRENCIES]]
code="MTLTH"
name="MTLTH"
issuer="GAEAAQ6GYMF6SSAWSW3MSLWB5LHYQIEGF3I3TUBJM6L3MSZYSPOMTLTH"
desc="MTLTH represents the ownership of investment fund assets that you can purchase if you want to support its activities and have your own stake of the fund. The top 20 shareholders are members of the Fund's Board of Directors, participating in the formulation and adoption of all decisions, including the collaborative management of this asset."
status="live"
display_decimals=7
anchor_asset_type="other"
is_unlimited=true
image="https://mtlth.montelibero.org/stellar-images/mtlth-logo.png"
